### ISSUE TITLE
SignalR and Kerberos.Net

### ISSUE THREAD

**Issue by johnnyreilly** [SteveSyfuhs/Kerberos.NET#129] opened 2020-01-25 09:20 UTC
**Is your feature request related to a problem? Please describe.**

Hey Steve,

Amazing work on Kerberos.Net! I'm dropping you a line as I've recently encountered a **hard problem**.

Hand on heart, I don't know how to solve it. I'm no expert on Auth (unlike yourself) but I have a feeling that I'm not the first to encounter this. I don't know for sure if I'm even asking good questions, but I thought I'd try. If I'm wasting your time please do forgive me.

Here's the situation: I have an ASP.Net Core 3.1 application which runs in docker + kubernetes on AWS. We've a need to connect our application to a SignalR hub that is hosted on an on-premise server. Our cluster has access to the on-premise network + server. However, that hub is secured via Windows Authentication. (A specific service account is permissioned to use it.) It would be amazing if that SignalR hub supported other Auth but alas that's not the case.

**Describe the solution you'd like**

So we've been wondering if there's a way to combine SignalR and Kerberos.Net to do this. It's possible this is already feasible, but despite much searching I haven't found an example of someone doing this.

I'm wondering if this is possible? Again, apologies for a random question from out of the blue. I'm an open source maintainer myself and I know that your time isn't free. If you're able to spend some time answering this that would be amazing. No sweat if not.

**Comment by SteveSyfuhs** [comment] 2020-01-27 16:51
Duplicate of https://github.com/dotnet/aspnetcore/issues/18576

**Closed by SteveSyfuhs** 2020-01-27 16:51 UTC
Labels: enhancement, help wanted
