### ISSUE TITLE
Overrided MR

### ISSUE THREAD

**Issue by Zubastic** [SteveSyfuhs/Kerberos.NET#210] opened 2020-10-26 16:08 UTC
**Describe the bug**
https://github.com/dotnet/Kerberos.NET/pull/166

MR overrided by 0b83e6b2e4183e17daece5b3cf12187a929b1771.

**Comment by SteveSyfuhs** [comment] 2020-10-26 16:50
This is a code regression because of the merge? Should be easy to fix.

**Comment by Zubastic** [comment] 2020-10-26 17:02
> This is a code regression because of the merge? Should be easy to fix.

Yep.

**Comment by SteveSyfuhs** [comment] 2021-05-25 20:35
This was fixed with #233

**Closed as completed by SteveSyfuhs** 2021-05-25 20:35 UTC
Labels: bug
